<a href="https://colab.research.google.com/github/ajaysaikiran2208/Natural-Language-Processing/blob/main/Simple_Transformer_Language_Model_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install transformers

     |████████████████████████████████| 2.5MB 5.2MB/s 
     |████████████████████████████████| 3.3MB 35.9MB/s 
     |████████████████████████████████| 901kB 48.9MB/s 


In [3]:
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("distilgpt2") 
model = AutoModelForCausalLM.from_pretrained("distilgpt2", output_hidden_states=True)

In [4]:
text = "The Prime Minister of India"

# Tokenize the input string
input = tokenizer.encode(text, return_tensors="pt")

# Run the model
output = model.generate(input, max_length=10, do_sample=False)

# Print the output
print('\n',tokenizer.decode(output[0]))

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.



 The Prime Minister of India, Narendra Modi, has


In [5]:
# Print the token ides (of the input and output)
output

tensor([[  464,  5537,  4139,   286,  3794,    11, 28113, 14637,    11,   468]])

In [6]:
# Print the input token ids
text = "The Prime Minister of India"
input = tokenizer(text, return_tensors="pt")['input_ids']
input

tensor([[ 464, 5537, 4139,  286, 3794]])

In [7]:

tokenizer.convert_ids_to_tokens(input[0])

['The', 'ĠPrime', 'ĠMinister', 'Ġof', 'ĠIndia']

In [8]:
import torch
import torchvision

In [9]:
# This is the embedding matrix of the model
model.transformer.wte # Dimensions are: (Number of tokens in vocabulary, dimension of model)

Embedding(50257, 768)

In [10]:
# Get the embedding vector of token # 464 ('The')
model.transformer.wte(torch.tensor(464))

tensor([-6.2649e-02, -4.4906e-02,  5.5888e-02, -5.4657e-02, -1.1713e-01,
        -7.2870e-02, -2.2326e-01, -3.2198e-03,  6.8535e-03,  2.3608e-02,
        -5.8700e-02,  4.4439e-02,  7.4774e-02, -1.3818e-02,  1.1873e-01,
        -5.1842e-02,  5.4415e-02,  5.5382e-02, -3.3126e-02,  1.1923e-01,
        -7.3283e-02,  2.6658e-02, -8.4261e-02,  5.7980e-02, -4.2860e-03,
        -4.0704e-02,  6.5652e-02, -6.6221e-02, -1.0232e-01,  3.1356e-02,
        -1.8873e-02,  2.7774e-02, -2.0423e-02,  1.1994e-01, -8.7572e-02,
        -1.0579e-01, -3.1816e-01,  9.5807e-02,  1.1588e-01, -4.2873e-02,
         1.3187e-01, -1.3457e-01, -1.0421e-01, -1.2150e-01,  9.2551e-02,
        -2.7394e-02,  3.1406e-02,  6.4891e-03,  1.2296e-01, -2.0581e-01,
        -6.3499e-02,  5.4726e-02,  6.0272e-02,  1.1968e-01,  6.4859e-02,
        -3.4885e-01, -5.6065e-02, -2.4721e-03,  3.7549e-03, -1.2817e-02,
        -8.4894e-02, -1.6269e-02,  8.2583e-02, -4.0134e-02, -2.1432e-01,
        -2.6889e-03,  1.5291e-02,  5.2090e-02,  2.9

In [17]:

text = "President of USA"

# Tokenize the input string
input = tokenizer.encode(text, return_tensors="pt")

# Run the model
output = model.generate(input, max_length=5, do_sample=True)

# Print the output
print('\n',tokenizer.decode(output[0]))

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.



 President of USA TODAY,
